### ISSUE TITLE
Lobo crashes when testing programs that use Navigation & UrlParser

### ISSUE THREAD

**Issue by squaresurf** [benansell/lobo#20]
I have a test that is testing that my json decoders work correctly, but am having some issues with case statements in my tests. For example:

```elm
test "json parser" <|
    \() ->
        case parseAllTheThings of
            Ok _ ->
                Expect.pass

            Err e ->
                Expect.fail e
```

I then went and broke the json, but I didn’t get any failures. So I tried this:

```elm
test "basic case statement" <|
    \() ->
        case 1 of
            1 ->
                Expect.fail "should fail"

            _ ->
                Expect.fail "would also fail"
```

Neither of those tests fail with elm-test or the lobo test extra frameworks. Once I switched to the elm-test cli runner the tests fail as expected.

Let me know if you need any other info and thank you for your hard work.

**Comment by benansell** [comment]
Thanks for reporting the issue. 

I have tried the basic case statement test and unfortunately it all appears to work for me locally. So we can work out what the issue is can you:
*  Check that the the other tests in the same file are running as part of the test suite
* Add the version of node and lobo being used
* Add the command line args being used to run lobo for either of the test frameworks

**Comment by squaresurf** [comment]
That's great news to hear that it works for you. I've recently switched to the elm-test cli runner as it's properly failing within the case statement. Here are some answers to your questions.

## Check that the the other tests in the same file are running as part of the test suite
If I remove the case statement and just `Expect.fail "oh noes"`, then it does fail the suite for lobo.

## Add the version of node and lobo being used
node v8.9.4
lobo version 0.4.1
elm version 0.18.0

This may not be important, but I'm using [asdf](https://github.com/asdf-vm/asdf) with the [asdf-elm plugin](https://github.com/vic/asdf-elmj) and the [asdf-nodejs plugin](https://github.com/asdf-vm/asdf-nodejs).


## Add the command line args being used to run lobo for either of the test frameworks
I'm currently running it with `lobo --framework elm-test`.

**Comment by squaresurf** [comment]
I forgot to add that if you still can't repro the issue, then I can create a basic elm app repo that reproduces the issue for me.

**Comment by benansell** [comment]
A repo that reproduces the issue would be great, as I am having no luck reproducing the issue.

**Comment by squaresurf** [comment]
Sounds good. I'll try to get to that soon.

**Comment by squaresurf** [comment]
Ok, I finally think I figured it out! It appears to be an issue with [Navigation.program](http://package.elm-lang.org/packages/elm-lang/navigation/2.1.0/Navigation#program). I created[lobo-case-example](https://github.com/squaresurf/lobo-case-example) with create-elm-app as a simple example for you to repro. Let me know if you're able to repro the issue.

**Comment by benansell** [comment]
Thanks for the failing test case - I am now able to reproduce the issue locally. You are correct that it is caused by Navigation.program - which internally calls document.location.getLocation(). Unfortunately  document.location is not one of the global properties initialised by lobo when running tests, which results in an exception being thrown and none of the tests being run.

I am working on a fix now, and I will update this issue when it is available on npm.

**Comment by benansell** [comment]
@squaresurf I have published an update to lobo that I believe fixes the issue you were having. 

If possible can you try updating to v0.4.2 and confirm that this fixes the issue?

**Comment by squaresurf** [comment]
It's working my simple example repo, but still isn't working for the project I'd like to use it with.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/863076/36916779-b8c1f9fc-1e09-11e8-87b6-1f02a3abdf99.png">

Do you have instructions for how to debug? How did you see the exception that was being thrown?

**Comment by benansell** [comment]
I am happy to have a look at the repo that is causing the issue if you provide a link / access?

Failing that I could try and help using the output from running lobo with --veryVerbose flag

**Comment by squaresurf** [comment]
Thank you for the offer, but I've not posted my code anywhere as of yet and it has quite a ways to go before I want to do so. Thank you for explaining the --veryVerbose flag. I was able to diagnose that we also have an issue with [UrlParser]. I pushed 2 commits to [lobo-case-example](https://github.com/squaresurf/lobo-case-example). One to prove that you fixed the issue with [Navigation.program](http://package.elm-lang.org/packages/elm-lang/navigation/2.1.0/Navigation#program) and another commit to make it easy to reproduce the issue with [UrlParser]. Let me know if you need any other info.

[UrlParser]: http://package.elm-lang.org/packages/evancz/url-parser/2.0.1

**Comment by squaresurf** [comment]
On another note, should I update this issue to reflect the fact that there are no issues with case statements?

**Comment by benansell** [comment]
Thanks for updating the test case repo. I have updated the global objects contain empty string for the following: document.location: { hash: "", pathname: "", search: "" }
This appears to be enough to allow the program to initialise with UrlParser.parsePath. 

I have also updated the logging to try and make this process a bit easier by outputting the stack trace on these types of errors. You should be able to use the --verbose flag to see the stack trace if there is another missing global.

Can you try updating to v0.4.3 and check if this fixes the issue?

**Comment by squaresurf** [comment]
It's fixed 🎉 

Thank you for all your hard work!
